config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "/tasks", to: "tasks#index", as: :tasks
  get "/tasks/new", to: "tasks#new", as: :task_new
  post "/tasks", to: "tasks#create"

  get "/tasks/:id", to: "tasks#show", as: :task

  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit
  patch "/tasks/:id", to: "tasks#update"

  delete "/tasks/:id", to: "tasks#destroy", as: :task_delete



  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: 'task was sucessfully dealeted'
  end



  private
  def task_params
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- app/views/layouts/application.html.erb -->
<!-- [...] -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="mb-4">Add Tasks</h1>
<%= form_with(model: @task, local: true, html: { class: "container mt-5" }) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Type..." %>
  </div>

  <div class="mb-3">
    <%= form.label :details, class: "form-label" %>
    <%= form.text_area :details, class: "form-control", placeholder: "Type...", row: 4  %>
  </div>

  <div class="actions">
    <%= form.submit "update Task", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
      <li>
        <%= link_to task.title, task_path(task) %>
        <%= form_with model: task, method: :delete, local: true do %>
          <%= submit_tag "Delete", class: "btn btn-danger btn-sm", data: { confirm: "Are you sure you want to delete this task?" } %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to "Create new task", task_new_path, class: 'btn btn-success' %>
</div>

app/views/tasks/new.html.erb
<h1 class="mb-4">Add Tasks</h1>
<%= form_with(model: @task, local: true, html: { class: "container mt-5" }) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Type" %>
  </div>

  <div class="mb-3">
    <%= form.label :details, class: "form-label" %>
    <%= form.text_area :details, class: "form-control", placeholder:"type", row: 4 %>
  </div>

  <div class="actions">
    <%= form.submit "Create Task", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/show.html.erb
<div class="container mt-3">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <p>completed : <%= @task.completed %></p>
  <%= link_to 'Back to tasks', tasks_path, class: "btn btn-success" %>
  <%= link_to task_edit_path(@task), class: 'btn btn-light' do %>
    <i class="fa-solid fa-pencil"></i>
  <% end %>
</div>